<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>name</key>
    <string>Stencil for YAML</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>include</key>
            <string>text.stencil</string>
        </dict>
        <dict>
            <key>include</key>
            <string>source.yaml</string>
        </dict>
    </array>
    <key>scopeName</key>
    <string>source.yaml.stencil</string>
    <key>uuid</key>
    <string>9C2B3E5F-8A7E-41A6-94B8-3F6F2B92A1D1</string>
    
</dict>
</plist>


